apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java4-ingress
  labels:
    app: java4
    backstage.io/kubernetes-id: java4 
spec:
  rules:
    - host: api-java4-anderson-dev.empcbr.thoughtworks-labs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java4
                port: 
                  number: 80
  tls:
  - hosts:
    - api-java4-anderson-dev.empcbr.thoughtworks-labs.net
    secretName: letencryptkey
---
apiVersion: v1
kind: Service
metadata:
  name: java4
  labels:
    app: java4
    backstage.io/kubernetes-id: java4
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: java4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java4
  labels:
    app: java4
    backstage.io/kubernetes-id: java4
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: java4
  template:
    metadata:
      labels:
        app: java4
    spec:
      containers:
      - name: java4
        image: 626109959667.dkr.ecr.us-east-1.amazonaws.com/java4:{image-tag}
        ports:
        - containerPort: 8080